# route configuration
transcript_route: /transcript
embedding_route: /register

# model configuration
transcript_model: ./Models/iic/SenseVoiceSmall
vad_model: ./Models/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch
embedding_model: ./Models/embeddingsExtractor
modelscope_cache: ./Models

# simularity threshold
simularity_threshold: 0.3